# ABOUTME: Schema definitions and tests for gold layer analytics tables
# ABOUTME: Ensures data quality and business logic integrity for production-ready analytics

version: 2

models:
  - name: dim_breeds
    description: >
      Gold layer analytics table containing comprehensive breed information.
      Combines breed identifiers, names, temperament, weight, and life span
      metrics in a single denormalized table for easy querying and analysis.

    columns:
      - name: breed_id
        description: Unique identifier for the breed from the Dog API
        tests:
          - not_null
          - unique

      - name: breed_name
        description: Name of the dog breed

      - name: temperament
        description: Personality and behavioral traits of the breed

      - name: weight_class_kg
        description: Weight range in metric units (kg) as string

      - name: life_span_max_years
        description: Maximum life span in years extracted from life_span string
