# ABOUTME: Schema definitions and tests for gold layer analytics tables
# ABOUTME: Ensures data quality and business logic integrity for production-ready analytics

version: 2

models:
  - name: dim_breeds
    description: >
      Table containing comprehensive breed information. It has one row per dog breed.

    columns:
      - name: breed_id
        description: Unique identifier for the breed from the Dog API
        tests:
          - not_null
          - unique

      - name: breed_name
        description: Name of the dog breed

      - name: temperament
        description: Personality and behavioral traits of the breed

      - name: weight_class_kg
        description: Weight range in metric units (kg) as string

      - name: life_span_max_years
        description: Maximum life span in years extracted from life_span string
        tests:
          - dbt_utils.accepted_range:
              min_value: 3
              max_value: 30

  - name: breed_temperaments
    description: >
      Normalized breed-temperament mapping table. Each row represents a single
      temperament trait for a breed.

    columns:
      - name: breed_id
        description: Unique identifier for the breed from the Dog API

      - name: temperament
        description: Individual temperament trait for the breed
