version: 2

sources:
  - name: dog_breeds_raw
    description: >
      Raw dog breed data ingested from the Dog API via dlt pipelines.
      Contains JSON-formatted breed information including physical characteristics,
      temperament, and metadata. This is the bronze layer in our medallion architecture.

    database: pyne-de-assignemet
    schema: dog_breeds_raw

    # Ideally we would like to test data source freshness. This check is not implemented as it would not make any sense to put it inside the cicd after the dlt ingesiton
    freshness:
      warn_after: {count: 10, period: day} 
      error_after: {count: 14, period: day}

    loaded_at_field: updated_at

    tables:
      - name: dog_breeds_resource
        description: >
          Core table containing dog breed information as JSON objects.
          Each row represents a single dog breed with comprehensive details
          stored in the breed_json column.

        columns:
          - name: row_id
            description: >
              Unique integer identifier for each row in the table.
              Auto-incremented by the ingestion pipeline.
            tests:
              - not_null
              - unique

          - name: breed_json
            description: >
              JSON object containing all breed information including:
              - id: unique breed identifier from the API
              - name: breed name
              - bred_for: original breeding purpose
              - breed_group: AKC breed classification
              - temperament: personality traits
              - life_span: typical lifespan range
              - weight: imperial and metric weight ranges
              - height: imperial and metric height ranges
              - reference_image_id: reference to breed image
            tests:
              - not_null

          - name: updated_at
            description: >
              Timestamp when the record was last updated in the raw table.
              Used for incremental processing and data freshness checks.
            tests:
              - not_null

          - name: _dlt_load_id
            description: >
              dlt pipeline load identifier. Links this record to a specific
              pipeline execution for traceability and debugging.
            tests:
              - not_null

          - name: _dlt_id
            description: >
              Unique identifier generated by dlt for each record.
              Used for deduplication and record tracking across loads.
            tests:
              - not_null
              - unique
